### Cluster and Outlier (Local Moran's I) Analysis results

In ArcGIS I ran the Cluster and Outlier tool to examine the relationship between the percentage of chinese people and restaurants per census tract across the urban/rural gradient.  In this notebook I examine the results and prepare the data for charting.

In [2]:
import pandas as pd

In [13]:
# load cluster/outlier results

clusters = pd.read_csv('ClusterOutlier_with_locales_ExportTable.csv')
print(clusters.shape)
clusters.head(-10)

(85045, 16)

,Join_Count,TARGET_FID,SOURCE_ID,rest_per_100ch,Loc_CODE,LOC_NAME,LMiIndex,LMiZScore,LMiPValue,COType,NNeighbors,ZTransform,SpatialLag,STATEFP,Shape_Length,Shape_Area
0,1,1,1,0.000000,12.0,Midsize City,0.012598,3.164750,0.002,LL,59294,-0.271019,-0.046485,1.0,8512.759369,4.337830e+06
1,2,2,2,0.000000,12.0,Midsize City,0.012987,2.916139,0.002,LL,59383,-0.271019,-0.047919,1.0,8365.285346,2.814555e+06
2,3,3,3,8.333334,12.0,Midsize City,-0.096205,-2.680670,0.002,HL,59084,3.250399,-0.029598,1.0,15315.079162,1.135523e+07
3,2,4,4,0.000000,32.0,Distant Town,0.011184,6.545516,0.002,LL,57886,-0.271019,-0.041268,1.0,22374.554442,2.906010e+07
4,3,5,5,0.000000,12.0,Midsize City,0.015381,5.134461,0.002,LL,53206,-0.271019,-0.056753,1.0,10749.134589,4.737048e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85030,1,85325,85325,0.000000,12.0,Midsize City,0.073451,1.325961,0.002,LL,938,-0.271019,-0.271019,72.0,4368.284256,1.100982e+06
85031,1,85326,85326,0.000000,21.0,Large Suburban,0.073451,5.808027,0.002,LL,938,-0.271019,-0.271019,72.0,5374.140375,1.481552e+06
85032,1,85327,85327,0.000000,12.0,Midsize City,0.073451,3.451234,0.002,LL,938,-0.271019,-0.271019,72.0,4187.149802,7.395314e+05
85033,2,85328,85328,0.000000,21.0,Large Suburban,0.073451,5.021216,0.002,LL,938,-0.271019,-0.271019,72.0,2490.258470,2.405732e+05
85034,2,85329,85329,0.000000,31.0,Fringe Town,0.073451,3.919190,0.002,LL,938,-0.271019,-0.271019,72.0,5151.558313,9.089639e+05

In [14]:
# determine STATEFP data type
clusters['STATEFP'].dtype

dtype('float64')

In [15]:
# get rows where STATEFP is null
clusters[clusters['STATEFP'].isnull()]

,Join_Count,TARGET_FID,SOURCE_ID,rest_per_100ch,Loc_CODE,LOC_NAME,LMiIndex,LMiZScore,LMiPValue,COType,NNeighbors,ZTransform,SpatialLag,STATEFP,Shape_Length,Shape_Area
251,0,252,252,0.0,NaN,NaN,0.012128,4.233406,0.002,LL,39002,-0.271019,-0.044749,NaN,9815.318939,5.658313e+06
17259,0,17289,17289,0.0,NaN,NaN,-0.027043,-5.698765,0.004,LH,24547,-0.271019,0.099786,NaN,12091.094807,4.338945e+06
17582,0,17612,17612,0.0,NaN,NaN,0.001731,0.451182,0.364,NaN,41029,-0.271019,-0.006387,NaN,53273.686647,9.586596e+07
20852,0,20882,20882,0.0,NaN,NaN,-0.008172,-2.906171,0.010,LH,35194,-0.271019,0.030153,NaN,109864.581807,9.279840e+07
33202,0,33305,33305,0.0,NaN,NaN,0.012608,3.359498,0.002,LL,34714,-0.271019,-0.046520,NaN,101455.948374,3.232715e+08
33501,0,33604,33604,0.0,NaN,NaN,0.011524,3.861136,0.002,LL,35186,-0.271019,-0.042521,NaN,121711.410937,5.056577e+08
34080,0,34192,34192,0.0,NaN,NaN,-0.025595,-13.010975,0.002,LH,24825,-0.271019,0.094440,NaN,2644.285370,3.127914e+05

In [17]:
# remove rows with null STATEFP
clusters = clusters[~clusters['STATEFP'].isnull()]

In [ ]:
# change STATEFP to integers
clusters['STATEFP'] = clusters['STATEFP'].astype(int)
clusters.head()

,Join_Count,TARGET_FID,SOURCE_ID,rest_per_100ch,Loc_CODE,LOC_NAME,LMiIndex,LMiZScore,LMiPValue,COType,NNeighbors,ZTransform,SpatialLag,STATEFP,Shape_Length,Shape_Area
0,1,1,1,0.000000,12.0,Midsize City,0.012598,3.164750,0.002,LL,59294,-0.271019,-0.046485,1,8512.759369,4.337830e+06
1,2,2,2,0.000000,12.0,Midsize City,0.012987,2.916139,0.002,LL,59383,-0.271019,-0.047919,1,8365.285346,2.814555e+06
2,3,3,3,8.333334,12.0,Midsize City,-0.096205,-2.680670,0.002,HL,59084,3.250399,-0.029598,1,15315.079162,1.135523e+07
3,2,4,4,0.000000,32.0,Distant Town,0.011184,6.545516,0.002,LL,57886,-0.271019,-0.041268,1,22374.554442,2.906010e+07
4,3,5,5,0.000000,12.0,Midsize City,0.015381,5.134461,0.002,LL,53206,-0.271019,-0.056753,1,10749.134589,4.737048e+06

In [21]:
# count rows where STATEFP is 72
clusters[clusters['STATEFP'] == 72].shape

(939, 16)

In [ ]:
# remove Puerto Rico for now
clusters = clusters[clusters['STATEFP'] != 72]
clusters.shape

(84099, 16)

In [24]:
# change Loc_CODE to integers
clusters['Loc_CODE'] = clusters['Loc_CODE'].astype(int)
clusters.head()

,Join_Count,TARGET_FID,SOURCE_ID,rest_per_100ch,Loc_CODE,LOC_NAME,LMiIndex,LMiZScore,LMiPValue,COType,NNeighbors,ZTransform,SpatialLag,STATEFP,Shape_Length,Shape_Area
0,1,1,1,0.000000,12,Midsize City,0.012598,3.164750,0.002,LL,59294,-0.271019,-0.046485,1,8512.759369,4.337830e+06
1,2,2,2,0.000000,12,Midsize City,0.012987,2.916139,0.002,LL,59383,-0.271019,-0.047919,1,8365.285346,2.814555e+06
2,3,3,3,8.333334,12,Midsize City,-0.096205,-2.680670,0.002,HL,59084,3.250399,-0.029598,1,15315.079162,1.135523e+07
3,2,4,4,0.000000,32,Distant Town,0.011184,6.545516,0.002,LL,57886,-0.271019,-0.041268,1,22374.554442,2.906010e+07
4,3,5,5,0.000000,12,Midsize City,0.015381,5.134461,0.002,LL,53206,-0.271019,-0.056753,1,10749.134589,4.737048e+06

In [ ]:
# check if any rows are not assigned to a locale
clusters[clusters['Loc_CODE'].isnull()].shape

(0, 16)

In [32]:
# number of tracts by cluster and locale type
clusters_grouped = clusters.groupby(['COType', 'Loc_CODE', 'LOC_NAME']).size().reset_index(name='count')
clusters_grouped['percentage'] = clusters_grouped['count'] / clusters_grouped['count'].sum() * 100
clusters_grouped

   COType  Loc_CODE          LOC_NAME  count  percentage
0      HH        11        Large City   2744    4.218488
1      HH        12      Midsize City    736    1.131490
2      HH        13        Small City    792    1.217581
3      HH        21    Large Suburban   3214    4.941043
4      HH        22  Midsize Suburban    154    0.236752
5      HH        23    Small Suburban    107    0.164496
6      HH        31       Fringe Town    150    0.230602
7      HH        32      Distant Town    115    0.176795
8      HH        33       Remote Town     53    0.081480
9      HH        41      Fringe Rural     71    0.109152
10     HH        42     Distant Rural     31    0.047658
11     HH        43      Remote Rural      7    0.010761
12     HL        11        Large City    456    0.701032
13     HL        12      Midsize City    326    0.501176
14     HL        13        Small City    364    0.559595
15     HL        21    Large Suburban    507    0.779436
16     HL        22  Midsize Suburban     64    0.098390
17     HL        23    Small Suburban     25    0.038434
18     HL        31       Fringe Town     62    0.095316
19     HL        32      Distant Town    112    0.172183
20     HL        33       Remote Town     87    0.133749
21     HL        41      Fringe Rural     20    0.030747
22     HL        42     Distant Rural      9    0.013836
23     HL        43      Remote Rural      4    0.006149
24     LH        11        Large City   5965    9.170292
25     LH        12      Midsize City   2064    3.173090
26     LH        13        Small City   2370    3.643519
27     LH        21    Large Suburban   8009   12.312635
28     LH        22  Midsize Suburban    719    1.105355
29     LH        23    Small Suburban    454    0.697957
30     LH        31       Fringe Town    870    1.337494
31     LH        32      Distant Town   1043    1.603456
32     LH        33       Remote Town    323    0.496564
33     LH        41      Fringe Rural   1212    1.863268
34     LH        42     Distant Rural   1016    1.561948
35     LH        43      Remote Rural    214    0.328993
36     LL        11        Large City   4550    6.994942
37     LL        12      Midsize City   2719    4.180054
38     LL        13        Small City   3304    5.079404
39     LL        21    Large Suburban   4456    6.850431
40     LL        22  Midsize Suburban    783    1.203745
41     LL        23    Small Suburban    602    0.925485
42     LL        31       Fringe Town   1270    1.952434
43     LL        32      Distant Town   3322    5.107076
44     LL        33       Remote Town   1886    2.899442
45     LL        41      Fringe Rural   3004    4.618199
46     LL        42     Distant Rural   3316    5.097852
47     LL        43      Remote Rural   1366    2.100020

In [33]:
# save as csv for charting
clusters_grouped.to_csv('clusters_grouped.csv', index=False)

In [36]:
# looking for proof that restaurant-to-chinese-population ratios are higher on average in small towns

from scipy import stats

urban_ratios = clusters[clusters['Loc_CODE'].isin([11, 12, 13])]['rest_per_100ch'].tolist()
suburban_ratios = clusters[clusters['Loc_CODE'].isin([21, 22, 23])]['rest_per_100ch'].tolist()
smalltown_ratios = clusters[clusters['Loc_CODE'].isin([31, 32, 33])]['rest_per_100ch'].tolist()
rural_ratios = clusters[clusters['Loc_CODE'].isin([41, 42, 43])]['rest_per_100ch'].tolist()

t_stat, p_value = stats.ttest_ind(urban_ratios, smalltown_ratios)

In [37]:
p_value

np.float64(6.222162859098869e-73)

In [38]:
t_stat

np.float64(18.09411895875736)

In [41]:
# calculate the mean of each list
urban_mean = sum(urban_ratios) / len(urban_ratios)
smalltown_mean = sum(smalltown_ratios) / len(smalltown_ratios)

# print the means
print(f"urban ratios mean: {urban_mean}")
print(f"smalltown ratios mean: {smalltown_mean}")

urban ratios mean: 0.7943989603274866
smalltown ratios mean: 0.3624839490172557

### Trying something else next

Something seems off. The results point to restaurant-to-chinese-population ratios being more clustered in urban areas, but I don't think that's exactly what I'm looking for.