In [14]:
import pandas as pd

In [15]:
# restaurant data with locale type
restaurants = pd.read_csv('restaurants-us.csv')
print(restaurants.shape)
restaurants.head()

(57536, 17)

,fsq_place_id,name,latitude,longitude,address,locality,region,postcode,country,date_created,date_refreshed,date_closed,still_open,LOCALE,STATEFP,GEO_YEAR,LOC_NAME
0,4c8c4e92cf3ea1434a7af451,Lee's Chinese,39.444009,-123.804738,154 E Redwood Ave,Fort Bragg,CA,95437.0,US,2010-09-12,2025-08-22,NaN,1,33.0,6.0,2024.0,Remote Town
1,4f442d5819836ed00192b620,China Express,39.433506,-123.805474,660 S Main St,Fort Bragg,CA,95437.0,US,2012-02-21,2025-07-3,NaN,1,33.0,6.0,2024.0,Remote Town
2,a194a71384e241d278559b60,Hill House Restaurant,39.310533,-123.798360,10701 Palette Dr,Mendocino,CA,95460.0,US,2012-05-21,2012-05-21,NaN,1,42.0,6.0,2024.0,Distant Rural
3,5dffd431f4a5f60008cfa1ce,Panda Express,39.130484,-123.198543,1236 Airport Park Blvd,Ukiah,CA,95482.0,US,2019-12-22,2025-07-3,NaN,1,33.0,6.0,2024.0,Remote Town
4,4f32482419836c91c7c8471b,New Dragon,39.140123,-123.205708,765 S State St,Ukiah,CA,95482.0,US,2012-02-8,2025-07-3,NaN,1,33.0,6.0,2024.0,Remote Town

In [16]:
# Change data type for postcode, LOCALE, and STATEFP to integers
restaurants['postcode'] = restaurants['postcode'].astype('Int64')
restaurants['LOCALE'] = restaurants['LOCALE'].astype('Int64')
restaurants['STATEFP'] = restaurants['STATEFP'].astype('Int64')

In [17]:
restaurants.head()

,fsq_place_id,name,latitude,longitude,address,locality,region,postcode,country,date_created,date_refreshed,date_closed,still_open,LOCALE,STATEFP,GEO_YEAR,LOC_NAME
0,4c8c4e92cf3ea1434a7af451,Lee's Chinese,39.444009,-123.804738,154 E Redwood Ave,Fort Bragg,CA,95437,US,2010-09-12,2025-08-22,NaN,1,33,6,2024.0,Remote Town
1,4f442d5819836ed00192b620,China Express,39.433506,-123.805474,660 S Main St,Fort Bragg,CA,95437,US,2012-02-21,2025-07-3,NaN,1,33,6,2024.0,Remote Town
2,a194a71384e241d278559b60,Hill House Restaurant,39.310533,-123.798360,10701 Palette Dr,Mendocino,CA,95460,US,2012-05-21,2012-05-21,NaN,1,42,6,2024.0,Distant Rural
3,5dffd431f4a5f60008cfa1ce,Panda Express,39.130484,-123.198543,1236 Airport Park Blvd,Ukiah,CA,95482,US,2019-12-22,2025-07-3,NaN,1,33,6,2024.0,Remote Town
4,4f32482419836c91c7c8471b,New Dragon,39.140123,-123.205708,765 S State St,Ukiah,CA,95482,US,2012-02-8,2025-07-3,NaN,1,33,6,2024.0,Remote Town

In [18]:
# fips codes table
fips = pd.read_csv('fips-codes.csv')
print(fips.shape)
fips.head()

(53, 3)

    STATENAME ABB  STATEFP
0     Alabama  AL        1
1      Alaska  AK        2
2     Arizona  AZ        4
3    Arkansas  AR        5
4  California  CA        6

In [19]:
# Change STATEFP data type to integers
fips['STATEFP'] = fips['STATEFP'].astype(int)

In [20]:
# Fill missing 'region' (state abbreviation) values in restaurants using STATEFP and fips 'ABB'
mask = restaurants['region'].isnull() | (restaurants['region'] == '')
restaurants.loc[mask, 'region'] = restaurants.loc[mask, 'STATEFP'].map(
    fips.set_index('STATEFP')['ABB']
)

In [ ]:
missing_region_df = restaurants[restaurants['region'].isnull() | (restaurants['region'] == "")]
missing_region_df.head()

,fsq_place_id,name,latitude,longitude,address,locality,region,postcode,country,date_created,date_refreshed,date_closed,still_open,LOCALE,STATEFP,GEO_YEAR,LOC_NAME
33667,4f64e862e4b08383b20e93d3,China Town On The Carnival Ecstasy,28.408986,-80.608692,NaN,NaN,NaN,<NA>,US,2012-03-17,2018-10-30,NaN,1,<NA>,<NA>,NaN,NaN
33803,4e503627b0fb088f3c278b4c,China Wall,30.381840,-81.569835,NaN,NaN,NaN,<NA>,US,2011-08-20,2018-03-29,NaN,1,<NA>,<NA>,NaN,NaN
37719,58895f4db12d9f308fb27347,You Yi City,32.556846,-116.620417,NaN,NaN,NaN,<NA>,US,2017-01-26,2017-06-26,NaN,1,<NA>,<NA>,NaN,NaN
37720,5699b7a0498e7617a2eaa499,Shi Qi,32.557451,-116.626676,NaN,NaN,NaN,<NA>,US,2016-01-16,2017-04-4,NaN,1,<NA>,<NA>,NaN,NaN
37721,4f3fea15e4b0a10c450ef476,Restaurant China Star,32.570213,-116.628069,NaN,NaN,NaN,<NA>,US,2012-02-18,2021-10-9,NaN,1,<NA>,<NA>,NaN,NaN

In [23]:
missing_region_df.shape

(8, 17)

In [25]:
restaurants.to_csv("restaurants-us-cleaned.csv", index=False)